### PR TITLE
Windows readme note

### PR DESCRIPTION
**Pull request by clach04**
Fix typo, and make one-liner command more clear and simple

### CODE REVIEW

**Comment by danny0838** [comment]
This is not a typo. The original doc says the user can run two commands—`D:` and `cd D:\path\to\scrapbook`—to switch CWD to `D:\path\to\scrapbook` from another drive.

**Comment by clach04** [comment]
> This is not a typo. The original doc says the user can run two commands—`D:` and `cd D:\path\to\scrapbook`—to switch CWD to `D:\path\to\scrapbook` from another drive.

That's the 2nd change that simplified the command into a one-liner. The first change to `requied` is to correct the typo.

I can update the commit message if you have a suggestion on how to make it more clear.

**Comment by danny0838** [comment]
Sorry for missing that. Please separate the typo fix and the drive changing to 2 commits. We are considering whether and how to deal with the latter. At least we don't want the double "for example" for now.

**Comment by clach04** [comment]
Apologies for not getting back to this sooner, been a busy couple of weeks :(

I was just about to make changes and spotted you have made some updates 👍 - thank you!

**Pull request closed without merging**
